import { IColorScale } from './index';
export declare const Tomato: IColorScale;
export declare const Red: IColorScale;
export declare const Crimson: IColorScale;
export declare const Pink: IColorScale;
export declare const Plum: IColorScale;
export declare const Purple: IColorScale;
export declare const Violet: IColorScale;
export declare const Indigo: IColorScale;
export declare const Blue: IColorScale;
export declare const Cyan: IColorScale;
export declare const Teal: IColorScale;
export declare const Green: IColorScale;
export declare const Grass: IColorScale;
export declare const Orange: IColorScale;
export declare const Brown: IColorScale;
export declare const Colors: {
  Tomato: IColorScale;
  Red: IColorScale;
  Crimson: IColorScale;
  Pink: IColorScale;
  Plum: IColorScale;
  Purple: IColorScale;
  Violet: IColorScale;
  Indigo: IColorScale;
  Blue: IColorScale;
  Cyan: IColorScale;
  Teal: IColorScale;
  Green: IColorScale;
  Grass: IColorScale;
  Orange: IColorScale;
  Brown: IColorScale;
};
